<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class VolCertsTableControllerTest extends WebTestCase
{
    const VHX = '/var/www/volcerts.vhx.cloud/tests/var';
    const LCL = '/Users/rick/Sites/AYSO/_dev/volcerts/tests/var';

    /**
     * @var string
     */
    private string $var;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        switch ($_SERVER['HOME']) {
            case "/home/vagrant":
                $this->var = self::VHX;
                break;
            default:
                $this->var = self::LCL;
        }
    }

    public function testRoot()
    {
        $client = static::createClient();

        $client->followRedirects();
        $client->request('GET', '/response');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }

    public function testEmptyId()
    {
        $client = static::createClient();

        $client->request('GET', '/id/');

        $this->assertEquals(301, $client->getResponse()->getStatusCode());
    }

    public function testId()
    {
        $client = static::createClient();

        $client->request('GET', '/id/97815888');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $html = str_replace("\u003Cbr\u003E", "",$client->getResponse()->getContent());
        $this->assertStringContainsString('"AYSOID":97815888', $html);
        $this->assertStringContainsString('"FullName":"Frederick Roberts"', $html);
        $this->assertStringContainsString('"CoachCertDate":"2018-08-29', $html);
        $this->assertStringContainsString('"CoachCertDesc":"Z-Online U-10 Coach', $html);
        $this->assertStringContainsString('"InstEvalCertDate":"2006-02-10"', $html);
        $this->assertStringContainsString('"InstEvalCertDesc":"Referee Instructor Evaluator"', $html);
        $this->assertStringContainsString('"InstCertDate":"2012-07-01"', $html);
        $this->assertStringContainsString('"InstCertDesc":"National Referee Instructor"', $html);
        $this->assertStringContainsString('"AssessorCertDate":"2004-04-09"', $html);
        $this->assertStringContainsString('"AssessorCertDesc":"National Referee Assessor"', $html);
        $this->assertStringContainsString('"RefCertDate":"2004-04-14"', $html);
        $this->assertStringContainsString('"RefCertDesc":"National Referee"', $html);
        $this->assertStringContainsString('"SCADate":"2020-06-17"', $html);
        $this->assertStringContainsString('"CDCDate":"2018-11-29"', $html);
        $this->assertStringContainsString('"SafeHavenDate":"2020-07-17"', $html);
        $this->assertStringContainsString('"MY":"MY202', $html);
        $this->assertStringContainsString('"SAR":"1\/D\/0092"', $html);
        $this->assertStringContainsString('"Type":"Adult"', $html);
        $this->assertStringContainsString('"DataSource":"e3"', $html);
    }

    public function testIds()
    {
        $client = static::createClient();

        $client->request('GET', '/id/97815888,96383440');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }

    public function testCSVUpload()
    {
        $client = static::createClient();

        copy($this->var . '/files/Book.3.csv', $this->var . '/uploads/Book.3.csv');
        $file = new UploadedFile(
            $this->var .'/uploads/Book.3.csv',
            'Book.3.csv',
            'text/csv',
            null
        );

        $client->request(
            'POST',
            '/ch',
            [],
            ['uploadFilename' => $file]
        );

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertStringContainsString('Upload another file', $client->getResponse()->getContent());
    }

    public function testBadUpload()
    {
        $client = static::createClient();

        copy($this->var . '/files/Book.3.bad.csv', $this->var . '/uploads/Book.3.bad.csv');
        $file = new UploadedFile(
            $this->var .'/uploads/Book.3.bad.csv',
            'Book.3.bad.csv',
            'text/csv',
            null
        );

        $client->request(
            'POST',
            '/ch',
            [],
            ['uploadFilename' => $file]
        );

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertStringContainsString('Upload another file', $client->getResponse()->getContent());
    }

    public function testXLSUpload()
    {
        $client = static::createClient();

        copy($this->var . '/files/Book.3.xls', $this->var . '/uploads/Book.3.xls');
        $file = new UploadedFile(
            $this->var .'/uploads/Book.3.xls',
            'Book.3.xls',
            'application/vnd.ms-excel',
            null
        );

        $client->request(
            'POST',
            '/ch',
            [],
            ['uploadFilename' => $file]
        );

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertStringContainsString('Upload another file', $client->getResponse()->getContent());
    }

    public function testXLSXUpload()
    {
        $client = static::createClient();

        copy($this->var . '/files/Book.3.xlsx', $this->var . '/uploads/Book.3.xlsx');
        $file = new UploadedFile(
            $this->var .'/uploads/Book.3.xlsx',
            'Book.3.xlsx',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            null
        );

        $client->request(
            'POST',
            '/ch',
            [],
            ['uploadFilename' => $file]
        );

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertStringContainsString('Upload another file', $client->getResponse()->getContent());
    }


}
